version: '3'
services:
  web:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html